name: splited
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.7
  http: ^0.12.2
  dartz: ^0.9.1
  freezed_annotation: ^0.11.0+1
  flutter_bloc: ^6.0.1
  native_color: ^1.2.0+1
  flare_flutter: ^2.0.6
  hydrated_bloc: ^6.0.1
  firebase_core: ^0.4.5
  google_sign_in: ^4.5.1
  flutter_facebook_login: ^3.0.0
  firebase_auth: ^0.16.1
  injectable: ^1.0.4
  get_it: ^4.0.4
  cloud_functions: ^0.5.0
  simple_tooltip: ^0.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.8
  build_runner: 1.10.1
  freezed: ^0.11.5
  bloc_test: ^7.0.0
  flutter_launcher_icons: ^0.7.5
  lint: ^1.2.0
  injectable_generator: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - lang/
    - assets/SplashScreen/
    - assets/HomePage/
    - assets/Core/
    - assets/RegisterPage/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/build/icon.png"
